name: flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/menus/ic_search_menu.png
    - assets/images/menus/ic_account.png
    - assets/images/menus/ic_cart.png
    - assets/images/menus/ic_home.png
    - assets/images/menus/ic_delete.png
    - assets/images/menus/ic_near_by.png
    - assets/images/menus/ic_credit_card.png
    - assets/images/menus/ic_app_icon.png
    - assets/images/menus/ic_food_express.png
    - assets/images/menus/ic_app_icon_black.png
    - assets/images/topmenu/ic_burger.png
    - assets/images/topmenu/ic_cake.png
    - assets/images/topmenu/ic_ice_cream.png
    - assets/images/topmenu/ic_pasta.png
    - assets/images/topmenu/ic_pizza.png
    - assets/images/topmenu/ic_sushi.png
    - assets/images/topmenu/ic_soft_drink.png
    - assets/images/popular_foods/ic_popular_food_1.png
    - assets/images/popular_foods/ic_popular_food_2.png
    - assets/images/popular_foods/ic_popular_food_3.png
    - assets/images/popular_foods/ic_popular_food_4.png
    - assets/images/popular_foods/ic_popular_food_5.png
    - assets/images/popular_foods/ic_popular_food_6.png
    - assets/images/bestfood/ic_best_food_1.jpeg
    - assets/images/bestfood/ic_best_food_2.jpeg
    - assets/images/bestfood/ic_best_food_3.jpeg
    - assets/images/bestfood/ic_best_food_4.jpeg
    - assets/images/bestfood/ic_best_food_5.jpeg
    - assets/images/bestfood/ic_best_food_6.jpeg
    - assets/images/bestfood/ic_best_food_7.jpeg
    - assets/images/bestfood/ic_best_food_8.jpeg
    - assets/images/bestfood/ic_best_food_9.jpeg
    - assets/images/bestfood/ic_best_food_10.jpeg
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
